name: Preview Packages - pkg.pr.new

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        run: corepack enable && pnpm -v

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm ci:install

      - name: Build EC-Twoslash
        run: pnpm ci:build:twoslash
  
      - name: Publish packages
        run: pnpx pkg-pr-new publish --pnpm --compact './packages/*'

